openapi: 3.0.0
info:
  title: Documentación de las APIs
  version: 1.0.0
  description: Información de la integración de Users, Products, Cart
  contact:
    name: Dotto Martin
    url: https://www.linkedin.com/in/martin-miguel-dotto-1a3913141/
servers:
  - url: http://localhost:8080
    description: Servidor Local
paths:
  /api/cart/:
    get:
      summary: Get All Products in Cart
      responses:
        "200":
          description: List of products in the user's cart
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  payload:
                    type: array
                    items:
                      type: object
                      properties:
                        _id:
                          type: string
                        title:
                          type: string
                        description:
                          type: string
                        price:
                          type: number
    post:
      summary: Add Product to Cart
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                productId:
                  type: string
                  description: The ID of the product to add to the cart
                userId:
                  type: string
                  description: The ID of the user adding the product to the cart
      responses:
        "200":
          description: Product added to cart successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: Product added to cart successfully
                  payload:
                    type: object
                    properties:
                      _id:
                        type: string
                      userId:
                        type: string
                      products:
                        type: array
                        items:
                          type: object
                          properties:
                            _id:
                              type: string
                            title:
                              type: string
                            description:
                              type: string
                            price:
                              type: number
  /api/cart/addToCart:
    post:
      summary: Deprecated Endpoint
      deprecated: true
      responses:
        "405":
          description: This endpoint is deprecated, please use POST /api/cart instead
